.TH tmines 1
.SH NAME
tmines - Terminate Mines, a Minesweeper clone
.SH SYNOPSIS
.B tmines
[\fB\-a\fP] [\fB\-?\fP] [\fB\-\fPV] [\fB\-c\fP \fINUM\fP] [\fB\-h\fP \fIHEIGHT\fP] [\fB\-y\fP \fIHEIGHT\fP] [\fB\-s\fP \fISEED\fP] [\fB\-w\fP \fIWIDTH\fP]
[\fB\-x\fP \fIWIDTH\fP] [\fB\-\-autodiscover-only\fP] [\fB\-\-mine\-count\fP=\fINUM\fP] [\fB\-\-count\fP=\fINUM\fP]
[\fB\-\-height\fP=\fIHEIGHT\fP] [\fB\-\-seed\fP=\fISEED\fP] [\fB\-\-width\fP=\fIWIDTH\fP] [\fB\-\-help\fP] [\fB\-\-usage\fP]
[\fB\-\-version\fP]

.SH Description
Terminate Mines is a Minesweeper clone. 
